/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-02 08:27:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sist.com.BbsDto;
import java.util.List;
import sist.com.BbsDao;
import sist.com.MemberDto;

public final class bbslist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


public String arrow(int depth){
	String rs = "<img src='image/arrow.png' width='20px' height='20px'>";
	String nbsp = "&nbsp;&nbsp;&nbsp;&nbsp;";	//한칸씩 떨어트리는 규격.
	String ts = "";
	for(int i = 0; i < depth; i++){
		ts += nbsp;
	}
	return depth==0? "":ts + rs;	/* depth가 0이면 본문이고, 아니면 덧글이니까 이미지 여백을 반환해줌
									depth의 개수에 따라 여백을 늘려서 마지막에 이미지 추가 */
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("sist.com.BbsDao");
    _jspx_imports_classes.add("sist.com.BbsDto");
    _jspx_imports_classes.add("sist.com.MemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 지금 로그인 된 회원 정보를 알아야 함. session에 담아놓음.     -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

BbsDao dao = BbsDao.getInstance();
List<BbsDto> bbslist = dao.getBbsList();




      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table{\r\n");
      out.write("\tborder-collapse:collapse;\r\n");
      out.write("}\r\n");
      out.write("table, th, td{\r\n");
      out.write("\tboder: 1px solid black;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("th{\r\n");
      out.write("\tbackground-color: green;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write(".tda{\r\n");
      out.write("\tbackground-color: #abcdef;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write(".tdb{\r\n");
      out.write("\tbackground-color: #febdab;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>bbslist</title>\r\n");
      out.write("<script>\"undefined\"==typeof CODE_LIVE&&(!function(e){var t={nonSecure:\"55291\",secure:\"55296\"},c={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=c[n]+r[n]+\":\"+t[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document),CODE_LIVE=!0);</script></head>\r\n");

Object ologin = session.getAttribute("login");		//로그인 한 멤버의 정보
MemberDto mem = null;
if(ologin == null){
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\talert(\"로그인 합시다\");\r\n");
      out.write("\t\tlocation.href =\"index.jsp\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
 
	return;		//ologin == null 에 걸리면 밑에 있는 작업들은 안하게 됨; 
}
mem = (MemberDto)ologin;

      out.write("    \r\n");
      out.write("\r\n");
      out.write("<body data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-4\" data-genuitec-path=\"/Jsp_BBS/WebContent/bbslist.jsp\">\r\n");
      out.write("\r\n");
      out.write("<h3 data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-4\" data-genuitec-path=\"/Jsp_BBS/WebContent/bbslist.jsp\">환영합니다");
      out.print(mem.getName() );
      out.write("님 반갑습니다.</h3>\r\n");
      out.write("\r\n");
      out.write("<a href='calendar.jsp'>일정보기</a>\r\n");
      out.write("\r\n");
      out.write("<a href='pdslist.jsp'>자료실</a>\r\n");
      out.write("\r\n");
      out.write("<a href='logout.jsp'>로그아웃</a>\r\n");
      out.write("\r\n");
      out.write("<hr/>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("<col width=\"50\"/><col width=\"50\"/><col width=\"150\"/><col width=\"500\"/><col width=\"150\"/>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>순서</th><th>시퀀스</th><th>정보</th><th>제목</th><th>작성자</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

if(bbslist == null || bbslist.size() == 0){

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\">작성된 글이 없다</td>\r\n");
      out.write("\t</tr>\r\n");

}
for(int i = 0; i<bbslist.size(); i++){
	BbsDto dto = bbslist.get(i);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<tr ");
      out.print(i%2 == 0?"class='tda'":"class='tdb'" );
      out.write(">\r\n");
      out.write("\t\t<td>");
      out.print(i+1 );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(dto.getSeq() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(dto.getRef() );
      out.write('-');
      out.print(dto.getStep() );
      out.write('-');
      out.print(dto.getDepth() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(arrow(dto.getDepth()) );
      out.write(" <!-- depth에 따라 여백을 늘릴지 말지 결정. arrow 0이든 1이든  -->\r\n");
      out.write("\t\t\t<a href='bbsdetail.jsp?seq=");
      out.print(dto.getSeq() );
      out.write("'>\r\n");
      out.write("\t\t\t");
      out.print(dto.getTitle() );
      out.write("\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>");
      out.print(dto.getId() );
      out.write("</td>\r\n");
      out.write("\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href='bbswrite.jsp'>글 쓰기</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
